### ISSUE TITLE
Verifying Single Signed Certificate

### ISSUE THREAD

**Issue by CITAcadAppsSupport** [GovTechSG/certificate-application#190]
Hi, i would like to build in house opencert file verification using ./index.js verify <PathToCertificate>,
the guide said below : 
Warning: Please verify this certificate on the blockchain with the issuer's certificate store.

does that mean we do have separate command? or still need to drop file at opencerts.io to make sure merkleroot stored at blockchain?

please advise, thank you.

regards,

**Comment by Nebulis** [comment]
I will add a deprecation notice but
- use https://github.com/Open-Attestation/oa-verify to verify v2 document
- use https://github.com/OpenCerts/verify/ to verify v1 and v2 documents

**Comment by CITAcadAppsSupport** [comment]
Hi @Nebulis noted and thanks
