### ISSUE TITLE
verification of the merkle root on blockchain

### ISSUE THREAD

**Issue by wmclaxton** [GovTechSG/certificate-application#39]
The documentation reads: “[OpenCerts Verification] does not verify that the batch's merkle root is stored on the blockchain. User will need to verify that the certificate has indeed been issued by checking with the issuer's smart contract."  However in our review of the source code it appears that the verification does include checking the blockchain hash.

Perhaps this bit of documentation is out of date and needs to amended.

**Comment by rjchow** [comment]
opencerts-website does validate against the blockchain, certificate-cli, open-certificate, and open-attestation only validates that the certificate proof is intact

https://github.com/OpenCerts/certificate-cli/blob/d8686c58fafe35b62fb71019f8cfc107141a31ce/index.js#L89
