### ISSUE TITLE
JSON schema version is not included in the unsigned cert

### ISSUE THREAD

**Issue by mmysgp** [GovTechSG/certificate-application#42]
Currently the JSON schema version is not included in the unsigned cert. It is only appended when it is signed using CLI and the version is always the latest version regardless the real version in the unsigned cert. This could create backward compatibility issues for SSG's SkillsFuture Portal as different logic need to be applied for different schema version to extract data.

Suggest to include JSON schema version in the unsigned cert and CLI not to change the schema version when generating hash. 

For consideration please.

**Comment by yehjxraymond** [comment]
Closing this issue as feature has been completed.

**Comment by mmysgp** [comment]
May I know what's the format in raw json to indicate schema version or via CLI parameter?

**Comment by rjchow** [comment]
call the cli without any arguments to see the detailed instructions
