### ISSUE TITLE
Invalide Document Error

### ISSUE THREAD

**Issue by sktumati** [GovTechSG/certificate-application#80]
Hi 
I am experiencing invalid document error while batching certificate. Please attached document for more details..
[Batching-Cert.docx](https://github.com/OpenCerts/certificate-cli/files/3491633/Batching-Cert.docx)

**Comment by yehjxraymond** [comment]
You are using an older version of the schema. Please see the updates for v2. You are highly encouraged to upgrade to v2. If you must use 1.4 or 1.5 please set the schema version in the CLI.

**Comment by yehjxraymond** [comment]
Also you may add images here directly without putting it into a docs.

**Comment by sktumati** [comment]
Installed new version and set the schema version. even though getting same error.
![image](https://user-images.githubusercontent.com/17443178/62861213-4deffa80-bd35-11e9-90aa-7bcca90e4e2e.png)

**Comment by yehjxraymond** [comment]
Use  the —schema flag

**Comment by sktumati** [comment]
Please let me know how to use schema flag.

**Comment by yehjxraymond** [comment]
add `--schema 1.5` to the same command. Closing this thread.
